### ISSUE TITLE
Can't install wekan on Raspbian

### ISSUE THREAD

**Issue by OskarNadolny** [j8r/DPlatform#36]
Again i can't install wekan on Raspbian, here is full log
```
Cloning into 'DPlatform-ShellCore'...
remote: Counting objects: 2748, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 2748 (delta 0), reused 0 (delta 0), pack-reused 2743
Receiving objects: 100% (2748/2748), 818.12 KiB | 203.00 KiB/s, done.
Resolving deltas: 100% (2062/2062), done.
Checking connectivity... done.
Obtaining the IPv4 address from http://ipv4.icanhazip.com...
done.
Cloning into 'meteor'...
remote: Counting objects: 2610, done.
remote: Compressing objects: 100% (2252/2252), done.
remote: Total 2610 (delta 233), reused 1458 (delta 132), pack-reused 0
Receiving objects: 100% (2610/2610), 14.26 MiB | 221.00 KiB/s, done.
Resolving deltas: 100% (233/233), done.
Checking connectivity... done.
It's the first time you've run Meteor from a git checkout.
I will download a kit containing all of Meteor's dependencies.
######################################################################## 100,0%
Installed dependency kit v0.5.16 in dev_bundle.

meteor: updating npm dependencies -- meteor-deque...
babel-compiler: updating npm dependencies -- meteor-babel...
ecmascript-runtime: updating npm dependencies -- meteor-ecmascript-runtime...
promise: updating npm dependencies -- meteor-promise...
ddp-client: updating npm dependencies -- faye-websocket, permessage-deflate...
npm-mongo: updating npm dependencies -- mongodb...
logging: updating npm dependencies -- cli-color...
xmlbuilder: updating npm dependencies -- xmlbuilder...
run: You're not in a Meteor project directory.

To create a new Meteor project:
  meteor create <project name>
For example:
  meteor create myapp

For more help, see 'meteor --help'.
mv: cannot move ‘bundle/..’ to ‘./..’: Device or resource busy
unbuild bcrypt@0.7.8
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine form-data@2.1.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
/
> bcrypt@1.0.2 install /home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v11-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@0.10.40 (node-v11 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/.node-gyp"
make: Entering directory '/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
make: *** No rule to make target '../.node-gyp/0.10.40/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/share/meteor/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.38-v7+
gyp ERR! command "/usr/local/share/meteor/dev_bundle/bin/node" "/usr/local/share/meteor/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/share/meteor/dev_bundle/bin/node /usr/local/share/meteor/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 4.4.38-v7+
node-pre-gyp ERR! command "node" "/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/share/meteor/dev_bundle/bin/node /usr/local/share/meteor/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/wekan/programs/server/npm/npm-bcrypt/node_modules/bcrypt/lib/binding' (1)

npm ERR! bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.2 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.38-v7+
npm ERR! command "/usr/local/share/meteor/dev_bundle/bin/node" "/usr/local/share/meteor/dev_bundle/bin/npm" "install" "bcrypt"
npm ERR! cwd /home/wekan/programs/server/npm/npm-bcrypt
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
unbuild bson@0.2.21
/
> bson@0.2.22 install /home/wekan/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/wekan/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make: Leaving directory '/home/wekan/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/bson/build'
bson@0.2.22 node_modules/bson
└── nan@1.8.4
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
/
> fibers@1.0.5 install /home/wekan/programs/server/node_modules/fibers
> node ./build.js

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/wekan/programs/server/node_modules/fibers/.node-gyp"
make: Entering directory '/home/wekan/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (tls == thread_id) {
   ^
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
  COPY Release/fibers.node
make: Leaving directory '/home/wekan/programs/server/node_modules/fibers/build'
Installed in `/home/wekan/programs/server/node_modules/fibers/bin/linux-arm-v8-3.14/fibers.node`
ansi-regex@0.2.1 node_modules/ansi-regex

ansi-styles@1.1.0 node_modules/ansi-styles

escape-string-regexp@1.0.3 node_modules/escape-string-regexp

chalk@0.5.1 node_modules/chalk

strip-ansi@0.3.0 node_modules/strip-ansi

supports-color@0.2.0 node_modules/supports-color

has-ansi@0.1.0 node_modules/has-ansi

eachline@2.3.3 node_modules/eachline

type-of@2.0.1 node_modules/type-of

amdefine@1.0.0 node_modules/amdefine

asap@2.0.3 node_modules/asap

underscore@1.5.2 node_modules/underscore

meteor-promise@0.5.0 node_modules/meteor-promise

promise@7.0.4 node_modules/promise

source-map-support@0.3.2 node_modules/source-map-support

semver@4.1.0 node_modules/semver

source-map@0.1.32 node_modules/source-map

fibers@1.0.5 node_modules/fibers
Created symlink from /etc/systemd/system/multi-user.target.wants/wekan.service to /etc/systemd/system/wekan.service.
```

**Comment by j8r** [comment]
Thank you Oskar. All is OK except the `bcrypt` module build fails,

**Comment by j8r** [comment]
I try on my side, this is really weird that Wekan is stuck to the prehistoric node 0.10.x. Normally the arm dev bundle ships all the package needed, but it doesn't appear to do the trick anymore.

Let's wait for Wekan devs to do like Rocket.Chat does: support meteor 1.4 with node.js 4 and this issues will be fixed.
This is the only app in DPlatform that still need this legacy node.js version, and we need to download it specially for Wekan.
Until this is done, the Wekan is depreciated.
